### ISSUE TITLE
Support for base 4.10 and ghc 8.2?

### ISSUE THREAD

**Issue by sebeaumont** [diagrams/diagrams-canvas#17]
When will support for base 4.10 and thus ghc 8.2 be available?

**Comment by byorgey** [comment]
Soon!  I am slowly working through a backlog of packages to update.

**Comment by sebeaumont** [comment]
Hi Brent, np thanks for the update - I’m going round updating some of my applications and megaparsec 6 is keeping me busy enough right now. I’ll stay tuned.

**Comment by byorgey** [comment]
`diagrams-canvas` is now updated on Hackage and should work with base 4.10 and GHC 8.2.  Let me know if you run into any issues.
